name: Docker Build and Push

on:
  push:
    branches:
      - main
      - dev
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout
        uses: actions/checkout@v4



   
        
      - name: Docker Login
        run: echo ${{ env.DOCKER_TOKEN}} | docker login -u ${{ env.DOCKER_USERNAME }} --password-stdin 
