# .github/workflows/ci.yml
name: Deploy to DockerHub

on:
  push:
    branches:
      - main
      - dev


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        run: echo "$DOCKERHUB_TOKEN" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t $DOCKERHUB_USERNAME/my-docker-image:${{ github.sha }} .
          docker push $DOCKERHUB_USERNAME/my-docker-image:${{ github.sha }}

      # Add other deployment steps...
