# .github/workflows/ci.yml
name: Frontend

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2


      - name: Docker Build
        uses: actions/docker-build@2
        with:
          dockerfile: Dockerfile


      - name: Docker Push
        uses: docker/docker-push@2  
        with:
          context:
          push: true
          tags:
            $DOCKER_USERNAME/puju:latest
          

