# .github/workflows/frontend-ci.yml
name: Frontend CI/CD

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

# .github/workflows/ci.yml
name: Combined CI

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Git SHA
        id: git_sha
        run: echo "::set-output name=sha::$(git rev-parse --short HEAD)"

      - name: Build Docker Image
        run: docker build -t $DOCKER_REPOSITORY:${{ steps.git_sha.outputs.sha }} .

      # Other steps...

      - name: Login to DockerHub
        run: echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin

      # Conditional step to push Docker image
      - name: Push Docker Image
        if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
        run: |
          docker push $DOCKER_REPOSITORY:${{ steps.git_sha.outputs.sha }}
