# .github/workflows/ci.yml
name: Frontend

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Confirm Pipeline
        run: |
          echo hello

        
      - name: Docker Build
        run: |
          docker build -t puju3366 .

